spring.application.name=AI-Interview-Platform

# ===============================
# MySQL Database
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/interview_platform
spring.datasource.username=root

spring.datasource.password=Allam@2006


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Server
# ===============================

server.port=8080